### ISSUE TITLE
Thumbs Up/ Down Page Jump

### ISSUE THREAD

**Issue by amcrawford** [amcrawford/idea-box.js#2]
@rrgayhart

Hey!  I didn't put this in my pull request but thought an issue might be an okay way to ask as well...

I have my thumb up and down functionality working so that you can click the icons, see the quality update without a page refresh and have the data save to the database but, the **icon click does make the view jump back to the top of the page.**

Here is a code-snippet of one of my methods that you can also find in ideas.js:

```
function likeIdea(id){
  $('#thumb-up' + id).on('click', function(){
    $.ajax($.getJSON('/api/v1/ideas/'+ id, function(idea){
      var newQuality = function(){
        if (idea.quality === 'swill'){
          return 'plausible'
        } else { return 'genius'}
      };
      $.ajax({
        type: 'PUT',
        url: '/api/v1/ideas/' + id + '.json',
        data: {
          idea: {quality: newQuality}
        },
        success: function(idea){
          $('#idea-quality' + id).html(newQuality);
        }
      })
    }))
  })
};
```

Let me know if you have any thoughts or if there it is better to stick to pull request communication as well!

**Comment by rrgayhart** [comment]
An issue works just fine! Have you tried an `event.preventDefault()` yet? http://api.jquery.com/event.preventDefault/

**Comment by rrgayhart** [comment]
[Here's some further reading on why!](http://stackoverflow.com/questions/3252730/how-to-prevent-a-click-on-a-link-from-jumping-to-top-of-page-in-jquery)

**Comment by amcrawford** [comment]
That fixed it! Thank you so much!
